a=input("1번 문장을 입력하세요: ")
b=input("2번 문장을 입력하세요: ")
c=input("3번 문장을 입력하세요: ")
f=open('test.txt','w')
f.write(a+"\n")
f.write(b+"\n")
f.write(c)
f=open('test.txt','r')
s=f.read()
print(s)
f.close()
f.close()
